# Generated by Django 6.0.6 on 2026-08-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('raca', models.CharField(max_length=80)),
                ('idade', models.IntegerField(default=0)),
            ],
        ),
    ]
