# Generated by Django 6.0.6 on 2026-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('concluida', models.BooleanField(default=False)),
                ('criada_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cachorro',
        ),
    ]
