# Generated by Django 6.0.6 on 2026-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefa_delete_cachorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
